include ../Makefile.common

# System modules
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += i2c_scan
USEMODULE += periph_rtc

# Project modules
USEMODULE += delay
EXTERNAL_MODULE_DIRS += $(CURDIR)/../../modules/delay

include $(RIOTBASE)/Makefile.include
