include ../Makefile.common

# System modules
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += i2c_scan
USEMODULE += periph_rtc
USEMODULE += xtimer

# Project modules
#USEMODULE += hello
#EXTERNAL_MODULE_DIRS += $(CURDIR)/../../modules/hello

include $(RIOTBASE)/Makefile.include
