FEATURES_REQUIRED += cpp
FEATURES_REQUIRED += periph_cpuid

# Storage (required)
USEMODULE += littlefs2
USEMODULE += mtd_sdcard

# Project modules (required)
USEMODULE += log_file
USEMODULE += settings
USEMODULE += triage

# Drivers
#USEMODULE += ds3231
#USEMODULE += sx127x

# Networking
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc
USEMODULE += netdev_default

# Project modules
USEMODULE += frames
USEMODULE += qtpy
