FEATURES_REQUIRED += cpp
FEATURES_REQUIRED += periph_cpuid

# Drivers
#USEMODULE += ds3231
#USEMODULE += sx127x

# Storage
USEMODULE += littlefs2
USEMODULE += mtd_sdcard

# Networking
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc
USEMODULE += netdev_default

# Project modules
USEMODULE += frames
USEMODULE += log_file
USEMODULE += qtpy
USEMODULE += settings
USEMODULE += triage
