include ../Makefile.common

# System modules
USEMODULE += ztimer_usec

# Project modules
USEMODULE += log_file
EXTERNAL_MODULE_DIRS += $(CURDIR)/../../sys/log_file

USEMODULE += settings
EXTERNAL_MODULE_DIRS += $(CURDIR)/../../sys/settings

USEMODULE += triage
EXTERNAL_MODULE_DIRS += $(CURDIR)/../../sys/triage

include $(RIOTBASE)/Makefile.include
