include ../Makefile.common

# System modules
USEMODULE += log
USEMODULE += ztimer_usec
USEMODULE += log_color

# Project modules
#USEMODULE += log_file
#EXTERNAL_MODULE_DIRS += $(CURDIR)/../../sys/log_file

include $(RIOTBASE)/Makefile.include
