include ../Makefile.common

# System modules
USEMODULE += shell
USEMODULE += xtimer

# Project modules
#USEMODULE += delay
#EXTERNAL_MODULE_DIRS += $(CURDIR)/../../modules/delay

include $(RIOTBASE)/Makefile.include
