include ../Makefile.common

# System modules
USEMODULE += shell
USEMODULE += ztimer_usec

# Project modules
#USEMODULE += progmem
#EXTERNAL_MODULE_DIRS += $(CURDIR)/../../modules/progmem

include $(RIOTBASE)/Makefile.include
