include ../Makefile.common

# System modules
USEMODULE += shell
USEMODULE += xtimer

# Project modules
#USEMODULE += hello
#EXTERNAL_MODULE_DIRS += $(CURDIR)/../../modules/hello

include $(RIOTBASE)/Makefile.include
