include ../Makefile.common

FEATURES_REQUIRED += cpp

# System modules
#USEMODULE += periph_rtc
USEMODULE += saul_default

# Shell
USEMODULE += gnrc_txtsnd
USEMODULE += ps
USEMODULE += shell
USEMODULE += shell_cmds_default
USEMODULE += shell_cmd_i2c_scan

# Project modules
USEMODULE += gps
USEMODULE += wsn

include $(RIOTBASE)/Makefile.include
