include ../Makefile.common

# System modules
USEMODULE += fmt
#USEMODULE += periph_rtc
USEMODULE += saul_default

# Shell
USEMODULE += i2c_scan
USEMODULE += shell
USEMODULE += shell_commands

# Project modules
USEMODULE += wsn

include $(RIOTBASE)/Makefile.include
