include ../Makefile.common

FEATURES_REQUIRED += cpp

# System modules
#USEMODULE += periph_rtc
USEMODULE += saul_default

# Shell
USEMODULE += i2c_scan
USEMODULE += gnrc_txtsnd
USEMODULE += ps
USEMODULE += shell
USEMODULE += shell_commands

# Project modules
USEMODULE += wsn

include $(RIOTBASE)/Makefile.include
